import { getNativeElementReferenceFromReactNativeDocumentElementInstanceHandle } from "react-native/types_generated/src/private/webapis/dom/nodes/internals/ReactNativeDocumentElementInstanceHandle";

getNativeElementReferenceFromReactNativeDocumentElementInstanceHandle